spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:todo_db}
    username: ${DB_USER:onebase}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    user: ${DB_USER:onebase}
    password: ${DB_PASSORD}
